# Init schema

# --- !Ups

create table MOODLY (
  ID VARCHAR(40) PRIMARY KEY,
  START TIMESTAMP NOT NULL,
  INTERVAL_DAYS NUMERIC(10) NOT NULL
);

create table BALLOT (
  ID SERIAL PRIMARY KEY,
  MOODLY_ID VARCHAR(40) NOT NULL REFERENCES MOODLY(ID),
  COOKIE_ID VARCHAR(40) NOT NULL,
  ITERATION_COUNT NUMERIC(10) NOT NULL,
  VOTE NUMERIC(1) NOT NULL
)

# --- !Downs

drop table BALLOT;

drop table MOODLY;

